# Generated by Django 5.1.7 on 2025-03-24 01:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Osteoporosis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="이름")),
                ("age", models.IntegerField(default=0, verbose_name="나이")),
                ("gender", models.CharField(max_length=10, verbose_name="성별")),
                ("height", models.IntegerField(default=0, verbose_name="키(cm)")),
                ("weight", models.IntegerField(default=0, verbose_name="몸무게(kg)")),
                (
                    "fracture",
                    models.BooleanField(default=False, verbose_name="골절 병력 여부"),
                ),
                (
                    "smoking",
                    models.BooleanField(default=False, verbose_name="흡연 여부"),
                ),
                (
                    "drinking",
                    models.BooleanField(default=False, verbose_name="음주 여부"),
                ),
                (
                    "calcitriol",
                    models.BooleanField(
                        default=False, verbose_name="비타민D 복용 여부"
                    ),
                ),
                (
                    "op",
                    models.BooleanField(
                        default=False, verbose_name="골다공증 진단 여부"
                    ),
                ),
                (
                    "ckd",
                    models.BooleanField(
                        default=False, verbose_name="만성 신장질환 여부"
                    ),
                ),
                (
                    "copd",
                    models.BooleanField(default=False, verbose_name="만성 폐질환 여부"),
                ),
                ("dm", models.BooleanField(default=False, verbose_name="당뇨병 여부")),
            ],
        ),
        migrations.CreateModel(
            name="OsteoporosisResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("major_risk", models.FloatField()),
                ("hip_risk", models.FloatField()),
                ("level", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
