# Generated by Django 5.1.7 on 2025-03-24 02:47

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("osteoporosis", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="osteoporosisresult",
            unique_together={("user", "name", "major_risk", "hip_risk", "level")},
        ),
    ]
