# Generated by Django 5.1.7 on 2025-03-24 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("osteoporosis", "0002_alter_osteoporosisresult_unique_together"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="osteoporosisresult",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="osteoporosisresult",
            name="age",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="osteoporosisresult",
            name="gender",
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name="osteoporosisresult",
            name="height",
            field=models.FloatField(null=True),
        ),
    ]
